version: '3'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=myStrongP@ssword
    ports:
      - "1433:1433"
    volumes:
      - conform-sql-data:/var/opt/mssql
volumes:
  conform-sql-data: